version: '3.8'

services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: demo-backend
    environment:
      SERVER_PORT: 8080
      DB_URL: r2dbc:postgresql://ep-rough-violet-adi6ri0k-pooler.c-2.us-east-1.aws.neon.tech/demo?sslmode=require&channel_binding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_pHT4NJx3gnSG
    ports:
      - "8080:8080"
    networks:
      - demo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./demo-front
      dockerfile: Dockerfile
    container_name: demo-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - demo-network
    restart: unless-stopped

networks:
  demo-network:
    driver: bridge
