spring:
  application:
    name: sjflasdfsf
  r2dbc:
    url: r2dbc:postgresql://asdlf;jadslfasfd/asdfasd?sslmode=require
    username: asdfa
    password: adfasdfasdfas
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

server:
  port: 8080

logging:
  level:
    io.r2dbc.postgresql: INFO
    org.springframework.r2dbc: INFO
    asfadsfdfs.sjflasdfsf: DEBUG