apiVersion: v1
kind: Secret
metadata:
  name: jhon-silva-38-secrets
  namespace: jhon-silva-38
type: Opaque
data:
  # Base de datos - Valores en base64
  # Para encodear: echo -n "tu-valor" | base64
  DB_URL: cjJkYmM6cG9zdGdyZXNxbDovL2RhZnNkZmEvYWRmc2FmP3NzbG1vZGU9cmVxdWlyZQ==
  DB_USERNAME: YXNkZmRhc2ZzYQ==
  DB_PASSWORD: YXNkZmFz
  SERVER_PORT: ODA4MA==