apiVersion: v1
kind: Secret
metadata:
  name: jhonbrayansilva-secrets
  namespace: jhonbrayansilva
type: Opaque
data:
  # Base de datos - Valores en base64
  # Para encodear: echo -n "tu-valor" | base64
  DB_URL: cjJkYmM6cG9zdGdyZXNxbDovL2FzZGxmO2phZHNsZmFzZmQvYXNkZmFzZD9zc2xtb2RlPXJlcXVpcmU=
  DB_USERNAME: YXNkZmE=
  DB_PASSWORD: YWRmYXNkZmFzZGZhcw==
  SERVER_PORT: ODA4MA==